import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Awesome Site!',
  description: 'Generated by NEXT + SANITY',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-5xl mx-auto py-7 px-10 md:px-10 lg:px-0 ">
          <header>
            <Link
              href="/"
              className='bg-gradient-to-r from-orange-400 via-red-500 bg-clip-text text-transparent to-purple-600 text-lg font-bold '
            >
              Shenon69
            </Link>
          </header>
          <main className='py-20'>{children}</main>
        </div>


      </body>
    </html>
  )
}
