import Link from 'next/link'
import '../globals.css'
import { Inter } from 'next/font/google'
import { getPages } from '@/sanity/sanity-utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Awesome Site!',
  description: 'Generated by NEXT + SANITY',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pages = await getPages();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-5xl mx-auto py-7 px-10 md:px-10 lg:px-0 ">
          <header className='flex items-center justify-between'>
            <Link
              href="/"
              className='text-gray-500 text-lg font-bold '
            >
              &lt;Stgp /&gt;
            </Link>
            <div className='flex items-center gap-3 text-gray-500 font-bold'>
              {pages.map((page) => (
                <Link key={page._id} href={`/${page.slug}`} className='hover:underline transition'>
                  {page.title}
                </Link>
              ))}
            </div>
          </header>
          <main className='py-20'>{children}</main>
        </div>


      </body>
    </html>
  )
}
